server:
  host: 0.0.0.0
  port: 5169

static:
  root_dir: public
  index_file: index.html
  auto_index: true
  routes:
    "/blogs": "blogs/index.html"

content_types:
  ".md": "text/markdown; charset=utf-8"
  ".css": "text/css; charset=utf-8"
  ".js": "text/javascript; charset=utf-8"
  ".json": "application/json; charset=utf-8"
  ".svg": "image/svg+xml; charset=utf-8"
  ".png": "image/png; charset=utf-8"
  ".jpg": "image/jpeg; charset=utf-8"
  ".jpeg": "image/jpeg; charset=utf-8"

